import type { Metadata } from 'next'

import './globals.css'

import { Anonymous_Pro } from 'next/font/google'

import Header from '@/components/common/Header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const Anonymous = Anonymous_Pro({
  weight: ['400', '700'],
  subsets: ['latin']
})

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${Anonymous.className} h-[calc(100vh-122px)] antialiased`}>
        <Header />
        <main className='relative h-full bg-santa bg-cover'>{children}</main>
      </body>
    </html>
  )
}
