import type { Metadata } from "next";
import "./globals.css";
import {Anonymous_Pro} from "next/font/google"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Anonymous = Anonymous_Pro({
  weight: ["400", "700"],
  subsets: ["latin"]
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Anonymous.className} bg-santa bg-cover antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
